server:
  port: 6601
spring:
  application:
    name: EUREKA-SERVER-6601
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    hostname: 127.0.0.1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka